export const ADD_DASHBOARD_ITEM = 'ADD_DASHBOARD_ITEM';

export const HANDLE_SEARCH = 'HANDLE_SEARCH';

export const DELETE_DASHBOARD_ITEM = 'DELETE_DASHBOARD_ITEM';

export const GET_SAVED_QUERIES = 'GET_SAVED_QUERIES';

export const LOAD_SAVED_QUERIES = 'LOAD_SAVED_QUERIES';

export const LOAD_SAVED_ERROR = 'LOAD_SAVED_ERROR';

export const LOAD_DASHBOARDS = 'LOAD_DASHBOARDS';

export const LOAD_DASHBOARD_INFO = 'LOAD_DASHBOARD_INFO';

export const UPDATE_DASHBOARD_INFO = 'UPDATE_DASHBOARD_INFO';

export const CLEAR_DASHBOARD_INFO = 'CLEAR_DASHBOARD_INFO';

export const MAP_OLD_ITEMS = 'MAP_OLD_ITEMS';

export const SAVE_DASHBOARD = 'SAVE_DASHBOARD';

export const HIDE_SAVED_DASHBOARD_MESSAGE = 'HIDE_SAVED_DASHBOARD_MESSAGE';

export const TOGGLE_DRY_RUN = 'TOGGLE_DRY_RUN';

export const TOGGLE_IS_PUBLIC = 'TOGGLE_IS_PUBLIC';

export const SELECT_PALETTE = 'SELECT_PALETTE';

export const CHANGE_COLORS = 'CHANGE_COLORS';

export const CHANGE_PICKER_COLORS = 'CHANGE_PICKER_COLORS';

export const CHANGE_DASHBOARD_TITLE = 'CHANGE_DASHBOARD_TITLE';

export const SHOW_TOOLBAR = 'SHOW_TOOLBAR';

export const CLOSE_TOOLBAR = 'CLOSE_TOOLBAR';

export const DRAG_START_HANDLER = 'DRAG_START_HANDLER';

export const DROP_HANDLER = 'DROP_HANDLER';

export const CHANGE_CHART_TITLE = 'CHANGE_CHART_TITLE';

export const CHANGE_CHART_SUBTITLE = 'CHANGE_CHART_SUBTITLE';

export const SET_LOADING = 'SET_LOADING';

export const SELECT_SAVED_QUERY = 'SELECT_SAVED_QUERY';

export const SAVED_QUERY_ERROR = 'SAVED_QUERY_ERROR';

export const CHANGE_CHART_TYPE = 'CHANGE_CHART_TYPE';

export const RESIZE_CHART = 'RESIZE_CHART';

export const STOP_RESIZE_CHART = 'STOP_RESIZE_CHART';

export const MOVE_CHART = 'MOVE_CHART';

export const STOP_MOVE_CHART = 'STOP_MOVE_CHART';

export const DELETE_CHART = 'DELETE_CHART';

export const CLOSE_SETTINGS = 'CLOSE_SETTINGS';

export const SHOW_SETTINGS = 'SHOW_SETTINGS';

export const SELECT_LEGEND_POSITION = 'SELECT_LEGEND_POSITION';

export const SELECT_SPARKLINE_OPTION = 'SELECT_SPARKLINE_OPTION';

export const SELECT_STACKING_OPTION = 'SELECT_STACKING_OPTION';

export const SET_SRC_FOR_IMG = 'SET_SRC_FOR_IMG';

export const SET_TEXT_FOR_PARAGRAPH = 'SET_TEXT_FOR_PARAGRAPH';

export const CLONE_CHART = 'CLONE_CHART';

export const TOGGLE_DASHBOARDS_MENU = 'TOGGLE_DASHBOARDS_MENU';

export const SET_NEW_DASHBOARD_FOR_FOCUS = 'SET_NEW_DASHBOARD_FOR_FOCUS';

export const SET_ACCESS_KEY = 'SET_ACCESS_KEY';

export const CLEAR_ACCESS_KEY = 'CLEAR_ACCESS_KEY';

export const CHANGE_SCREEN_SIZE = 'CHANGE_SCREEN_SIZE';

export const LOADING_SINGLE_DASHBOARD = 'LOADING_SINGLE_DASHBOARD';

export const FILTER_DASHBOARDS_MENU = 'FILTER_DASHBOARDS_MENU';

export const CHANGE_SORTING = 'CHANGE_SORTING';

export const COL_MOVE_CHART = 'COL_MOVE_CHART';

export const SET_PREFIX = 'SET_PREFIX';

export const SET_SUFFIX = 'SET_SUFFIX';

export const SELECT_SHOW_POINTS = 'SELECT_SHOW_POINTS';

export const SELECT_POINTS_SIZE = 'SELECT_POINTS_SIZE';

export const SELECT_CHOROPLETH_MAP = 'SELECT_CHOROPLETH_MAP';

export const SHOW_CHOROPLETH_BORDER = 'SHOW_CHOROPLETH_BORDER';

export const SELECT_CHOROPLETH_BORDER_SIZE = 'SELECT_CHOROPLETH_BORDER_SIZE';

export const SHOW_CHOROPLETH_SLIDERS = 'SHOW_CHOROPLETH_SLIDERS';

export const SHOW_HEATMAP_SLIDERS = 'SHOW_HEATMAP_SLIDERS';

export const SHOW_HEATMAP_TOOLTIP_VALUE = 'SHOW_HEATMAP_TOOLTIP_VALUE';

export const SET_THEME = 'SET_THEME';

export const SET_CHART_THEME = 'SET_CHART_THEME';

export const SET_LAYOUT = 'SET_LAYOUT';
