export const ADD_DASHBOARD_ITEM = "ADD_DASHBOARD_ITEM";

export const HANDLE_SEARCH = "HANDLE_SEARCH";

export const DELETE_DASHBOARD_ITEM = "DELETE_DASHBOARD_ITEM";

export const GET_SAVED_QUERIES = "GET_SAVED_QUERIES";

export const LOAD_SAVED_QUERIES = "LOAD_SAVED_QUERIES";

export const LOAD_SAVED_ERROR = "LOAD_SAVED_ERROR";

export const LOAD_LOCAL_STORAGE = "LOAD_LOCAL_STORAGE";

export const LOAD_DASHBOARD_INFO = "LOAD_DASHBOARD_INFO";

export const CLEAR_DASHBOARD_INFO = "CLEAR_DASHBOARD_INFO";

export const SAVE_DASHBOARD = "SAVE_DASHBOARD";

export const HIDE_SAVED_DASHBOARD_MESSAGE = "HIDE_SAVED_DASHBOARD_MESSAGE";

export const TOOGLE_DRY_RUN = "TOOGLE_DRY_RUN";

export const SELECT_PALETTE = "SELECT_PALETTE";

export const CHANGE_DASHBOARD_TITLE = "CHANGE_DASHBOARD_TITLE";

export const SHOW_TOOLBAR = "SHOW_TOOLBAR";

export const CLOSE_TOOLBAR = "CLOSE_TOOLBAR";

export const DRAG_START_HANDLER = "DRAG_START_HANDLER";

export const DROP_HANDLER = "DROP_HANDLER";

export const CHANGE_CHART_TITLE = "CHANGE_CHART_TITLE";

export const SET_LOADING = "SET_LOADING";

export const SELECT_SAVED_QUERY = "SELECT_SAVED_QUERY";

export const SAVED_QUERY_ERROR = "SAVED_QUERY_ERROR";

export const CHANGE_CHART_TYPE = "CHANGE_CHART_TYPE";

export const RESIZE_CHART = "RESIZE_CHART";

export const STOP_RESIZE_CHART = "STOP_RESIZE_CHART";

export const MOVE_CHART = "MOVE_CHART";

export const STOP_MOVE_CHART = "STOP_MOVE_CHART";

export const DELETE_CHART = "DELETE_CHART";

export const CLOSE_SETTINGS = "CLOSE_SETTINGS";

export const SHOW_SETTINGS = "SHOW_SETTINGS";

export const SELECT_LEGEND_POSITION = "SELECT_LEGEND_POSITION";

export const SELECT_SPARKLINE_OPTION = "SELECT_SPARKLINE_OPTION";

export const SELECT_STACKING_OPTION = "SELECT_STACKING_OPTION";

export const SET_SRC_FOR_IMG = "SET_SRC_FOR_IMG";

export const SET_TEXT_FOR_PARAGRAPH = "SET_TEXT_FOR_PARAGRAPH";

export const CLONE_CHART = "CLONE_CHART";

export const TOOGLE_DASHBOARDS_MENU = "TOOGLE_DASHBOARDS_MENU";
